version: '3.8'
services:
    wis2nodebench1:
      container_name: wis2nodebench1
      image: golfvert/benchmarkwis2gb:1.0.1
      environment:
        - TZ=Europe/Paris
        - MQTT_CONFIG_BROKER=
        - MQTT_CONFIG_USERNAME=
        - MQTT_CONFIG_PASSWORD=
        - MQTT_CONFIG_TOPIC=config/#
        - CENTRE_ID=100 # FOR CONTAINER01
        - MQTT_PUB_BROKER=mqtt://mosquitto
        - MQTT_PUB_USERNAME=mqtt
        - MQTT_PUB_PASSWORD=mqtt_secure
        - MQTT_PUB_BROKERVERSION=5
        - MQTT_PUB_QOS=1
      networks:
        - wis2bridge
      restart: unless-stopped
    wis2nodebench2:
      container_name: wis2nodebench2
      image: golfvert/benchmarkwis2gb:1.0.1
      environment:
        - TZ=Europe/Paris
        - MQTT_CONFIG_BROKER=
        - MQTT_CONFIG_USERNAME=
        - MQTT_CONFIG_PASSWORD=
        - MQTT_CONFIG_TOPIC=config/#
        - CENTRE_ID=120 # FOR CONTAINER02
        - MQTT_PUB_BROKER=mqtt://mosquitto
        - MQTT_PUB_USERNAME=mqtt
        - MQTT_PUB_PASSWORD=mqtt_secure
        - MQTT_PUB_BROKERVERSION=5
        - MQTT_PUB_QOS=1
      networks:
        - wis2bridge
      restart: unless-stopped   
    mosquitto:
      image: eclipse-mosquitto:2.0.15
      container_name: mosquitto
      volumes:
        - $HOME/mosquitto:/mosquitto
        - $HOME/mosquitto/data:/mosquitto/data
        - $HOME/mosquitto/log:/mosquitto/log
      ports:
        - 1883:1883
      networks:
        - wis2bridge
networks:
    wis2bridge:
      external: true
